monsieurbiz_sylius_settings:
    plugins:
        monsieurbiz.stuartDelivery:
            vendor_name: Monsieur Biz
            vendor_url: https://monsieurbiz.com/
            plugin_name: monsieurbiz_stuart_delivery_plugin.plugin_name
            description: monsieurbiz_stuart_delivery_plugin.description
            icon: box
            use_locales: false
            classes:
                form: MonsieurBiz\SyliusStuartDeliveryPlugin\Form\Type\SettingsType
            default_values:
                api_mode: '%env(resolve:MONSIEURBIZ_STUART_DELIVERY_API_MODE)%'
                api_client_id: '%env(resolve:MONSIEURBIZ_STUART_DELIVERY_API_CLIENT_ID)%'
                api_client_secret: '%env(resolve:MONSIEURBIZ_STUART_DELIVERY_API_CLIENT_SECRET)%'
